### ISSUE TITLE
QUESTION: New contributions are MIT licensed?

### ISSUE THREAD

**Issue by MasterOdin** [beekeeper-studio/beekeeper-studio#1046]
**Details:**
From [CONTRIBUTING.md](https://github.com/beekeeper-studio/beekeeper-studio/blob/62ba4dacb016d8b9ebd239cc1bd16a0ad949e470/CONTRIBUTING.md):

> All contributions to this repository are made under the [MIT License](https://opensource.org/licenses/MIT)

Should this read "made under the GPLv3 License"?

**Comment by MasterOdin** [comment]
This seems more complicated given the README says:
> Beekeeper Studio Community Edition (the code in this repository) is licensed under the GPLv3 license.

So someone makes a PR, and the code in the context of that PR is in MIT, but as soon as you hit "merge", you're sublicensing the code to GPLv3? Or is the code in this repo still only MIT, and only being sublicensed when you make a release?

**Comment by rathboma** [comment]
Let me ask them to clarify the wording

**Comment by DMouse10462** [comment]
Should this issue be kept open until the matter is resolved?

The current state of licensing post-#1039 isn't clear.

**Comment by DMouse10462** [comment]
Just to clarify, you are *sublicensing* the contributors' MIT-licensed code as GPLv3, correct? You must preserve the original MIT license notice somewhere in the codebase as well as in all distributed copies per the language, even your proprietary "Ultimate Edition" releases (emphasis mine):

> The above copyright notice and this permission notice shall be included in **all copies or substantial portions of the Software**.

Sublicensing doesn't mean that the original license fails to exist. You must preserve the notice (a lot of repositories create something like a LICENSE.mit file for this). It would also be good practice to use "sublicense" instead of "relicense" in CONTRIBUTING.md; "sublicense" is for licensing something you have been licensed to someone else while "relicense" is when the licensor provides a new license to the same grantee after, for example, an expiration of a previous license. This language also directly matches that of the MIT license, removing any ambiguity that you may be stepping outside the bounds of the original license.

**Comment by rathboma** [comment]
Hi David,

Thanks for your thoughts. I understand what you are saying. My docs have been run by an open source IP lawyers who does not have any issues with them. 

Nevertheless I will run some of these questions by them again to be sure.

Thanks,

Matthew

**Comment by DMouse10462** [comment]
Matthew,

Thanks for the prompt response. I take moral issue with other parts of this change - this opens up a rift of "MIT for me, GPLv3 for everyone else" between you and the other contributors - but this was the only thing that stood out as far as true MIT *violations* go.

Thanks,
David

**Comment by rathboma** [comment]
Hi David,

I've chatted with my lawyer, here is how our contribution licensing works. If you contribute, you still own your contributions, and they are licensed to the world -- including our project -- under MIT. Strictly speaking, that's not a sublicense, but open source is not really a sublicensing paradigm.

Our project as a whole -- which consists mostly of code we have written -- is under the license we choose, which is currently GPLv3. Lots of corporate open source projects work this way, using a permissive license like MIT for contributions.  

The alternative is to use a CLA (contributor licensing agreement), or to have contributors assign copyright to us on submission, but MIT is a familiar license, and so using it means a contributor doesn't have to read and digest a new set of terms that may be harder to understand. We want to be clear, straightforward, and transparent with our contribution terms.

I understand your moral objection to anything that is not license in=license out, but we need the flexibility to change our project license if we need to.

I've added a copy of the MIT license to the contributing.md file. Thanks!

**Comment by rathboma** [comment]
Going to lock this issue, as I don't think there's any value going back and forth on it. I certainly hope you don't see this as a moral issue, it's more a practical measure to save headaches in the future.

Thanks for talking with me about it. I think my contributing terms are clearer as a result :heart:
