### ISSUE TITLE
FEAT: double clicking on a table with tab already open should refresh it

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#1075]
**Is your feature request related to a problem? Please describe.**
1. double click on a table
2. a new tab is open, with all records. Perfect
3. double click on a table
4. a new tab is open, with all records.

**Describe the solution you'd like**
Step 4 should instead focus existing tab and refresh / reset filters

Thanks!

**Comment by rathboma** [comment]
So I'm not super sure what to do about this. If a user has a table open with a filter, should it switch to that view? What if a user clicks a foreign key from another table, should it take over the view, or open a new one?

That's why they each open a new tab right now. I'm not sure what combination of behaviors is correct.

**Comment by rathboma** [comment]
If you have a suggestion on how to handle tables with filters, please let me know

**Comment by mariusa** [comment]
Good question. One might query via filters for some specific rows, and might want another tab with other filters.

I guess the best would be:
clicking on a table/view object should...
1. if a view *without filters* already exists, switch to that view
2. else open a new view (current behavior)

**Comment by mariusa** [comment]
After more usage, I find opening separate tabs (current behavior) more convenient. Thanks for considering!
