### ISSUE TITLE
BUG: The app menu disappears on Windows with "Native" layout ON

### ISSUE THREAD

**Issue by Sushibainsho** [beekeeper-studio/beekeeper-studio#1123]
**Describe the bug**

On Windows, the "Native" layout option is available and make all the App menu disappear with no way to restore it. 
Even after an App quit/relaunch.

![s51WomEq3g](https://user-images.githubusercontent.com/102673107/160844947-1f50c4c3-e71a-4985-9df1-075f9dd1fbed.png)

**Step to reproduce: (Beware, not reversible)**

**To Reproduce**
(Beware, not reversible)
1. Having Beekeeper Studio 3.3.6 on Windows
2. Go to App settings / Theme
2. Select "Native" layout and apply

**Expected behavior**
Like expected [here](https://github.com/beekeeper-studio/beekeeper-studio/pull/241), the "Native" layout option should not be available on Windows.

**Screenshots / Gifs**

![s51WomEq3g](https://user-images.githubusercontent.com/102673107/160847459-58e54977-906f-463b-a750-b07f744e6c91.png)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version Beekeeper Studio 3.3.6
 - Database type and version : N/A

Thank you :)

**Comment by Patryk1098** [comment]
Thank you for reporting this bug. I have it also and it's making it difficult and inconvenient to use the app. :/
What's the other possible value? Because you can open the app.db file in the beekeeper-studio directory on your Window system and modify the value using BeeKeeper Studio.

I tried 'system' and 'default' to no effect. Just haven't dug through the code yet to find the possible values to see if changing them has an impact of if the most recent release hardcoded the setting.

**Comment by IndrekHaav** [comment]
> What's the other possible value?

The other possible value is "client".

```
update user_setting set userValue = 'client' where key = 'menuStyle';
```

**Comment by Sushibainsho** [comment]
@Patryk1098 @IndrekHaav Thank you very much for the workaround! It works :)

I let the issue open has the bug is still there.

Kind regards,

**Comment by rathboma** [comment]
Hey! I've fixed this and it will be included in the next point release (available today)

@IndrekHaav thanks for sharing the workaround!
