### ISSUE TITLE
Title and menu bar disappeared

### ISSUE THREAD

**Issue by vassbg** [beekeeper-studio/beekeeper-studio#1125]
After changing the theme to dark, title and menu bar disappeared!

The app is working, but I can't see or access the menu! 
ALT does nothing.

Reinstalling doesn't help.
OS is Windows 11

I love the app, please advise!
Screen:
<img width="956" alt="Screenshot 2022-03-30 222513" src="https://user-images.githubusercontent.com/7436256/160916086-98219a6e-dfd3-46b6-9d05-3b35a9456ad9.png">

**Comment by rathboma** [comment]
Did you have it on 'client' menu mode or 'native'?

I'll take a look at this tonight

**Comment by vassbg** [comment]
I am not shure and I can't see now... 
How can I make a clean reinstall?

**Comment by aeipathy** [comment]
This happened to me as well when setting view > menu > native

**Comment by IndrekHaav** [comment]
Happened to me as well, after upgrading to 3.3.6. Beekeeper Studio is installed through Chocolatey, though that shouldn't make a difference.

Instead of deleting the whole AppData folder, this can be fixed by opening Beekeeper Studio's own database (`%appdata%\beekeeper-studio\app.db`), viewing the table `user_setting` and changing the value of `menuStyle` to "client".

**Comment by vassbg** [comment]
Thanks!
