### ISSUE TITLE
BUG: content of a MySQL binary column looks wrong

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#1155]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20150243/162503837-f96aed62-022e-4f9e-9379-f4edbdf35f80.png)

I noticed in a similar program, that they display those binary content as hexadecimal which looks way better than those cryptic signs:
![image](https://user-images.githubusercontent.com/20150243/162503994-51f3c583-5891-4209-8745-d08f89996bd4.png)

**To Reproduce**
Install Shopware 6 and look at several tables, e. g. media_folder

**Expected behavior**
Hexadecimal or something different which doesn't look that cryptic.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 3.3.8
 - Database type and version MySQL 5.7.36

**Comment by rathboma** [comment]
Hey! Yes you're right. I'll take a look at it.

**Comment by BrianLeishman** [comment]
Also, I have a hunch this is related, but the Foreign key linking feature for binary columns doesn't appear to work 
![image](https://user-images.githubusercontent.com/1208702/164473943-487ec876-9d62-4eb9-91f3-ca7b6a8073e9.png)

**Comment by rathboma** [comment]
@BrianLeishman @Zerotask Ok, I'm looking at a similar issue so I want to look into this now as well.

Here's what Beekeeper does:
- If it finds a binary column it calls `toString` on the buffer
- This is why stuff looks weird.

What it *could* do:
- deserialize as hex or base64

Some questions to help me here:

- What are you storing in your binary primary keys? Eg are you serializing a UUID to binary?
- Some folks just store strings in binary columns: eg `insert into table_with_binary values ('9fad5e9eefdfb449')`, encoding as hex/base64 here wouldn't work as well.

@BrianLeishman can you provide me with simple CREATE TABLE and INSERT statements for test data to replicate your problem?

Ways to deal with this:

- [easy] Default to hex or base64 for decoding binary columns instead of the default
- [harder] Provide users with a setting to change the default decoding of binary columns

**Comment by rathboma** [comment]
Ok, I think a convention in MySQL is to prefix the hex value with `0x` and use it as a literal. Let me look at that. Doesn't help for other dbs though

**Comment by BrianLeishman** [comment]
Yup that makes sense! I was also looking at DataGrip from Jetbrains and DBeaver, and they both let you kind of choose the decoding type. They're smart about it, too, if I store UUIDs in a binary form with the time parts rearranged (for faster inserts), they actually recognize that and offer to show them as UUIDs. For things it doesn't recognize it lets me choose base64 encoding or hex encoding.

In my use case I'm storing 8 byte IDs that are custom to our application, but the data is purely binary. I've also used https://github.com/rs/xid, which stores as 12 bytes (we don't store things "encoded" since that makes the keys bigger).

I have my own repo that wraps the Go Xid library for use in MySQL: https://github.com/StirlingMarketingGroup/mysql-xid

Column type would be `BINARY(12)` and the insert looks like

```sql
insert into `table` (`ID`) values(0x604B7B580C43999B8B09D268)
```

You could also wrap with `from_base64()` like `from_base64('mFW8tzO/EDUw01NG')` but that's slower than the hex literals, not that probably matters in this use case.

**Comment by rathboma** [comment]
Awesome.

Yeah what I think I'm settling on is using hex decoding by default for all databases. That lets me move the encoding/decoding logic from the view layer to the database layer -- so stuff like FK lookups will actually work. I'll probably build a custom `binary editor` and a custom `binary viewer` in vue that lets you switch between encoding formats.

I can always then do something clever to detect UUIDs, although DataGrip has waaaaay more resources than me to do that kind of stuff :-D.

**Comment by azmy60** [comment]
The newest version should show binary in hex now. #1250
