### ISSUE TITLE
FEAT: allow each table to be opened once

### ISSUE THREAD

**Issue by comtom** [beekeeper-studio/beekeeper-studio#1247]
When clicking in the left panel a table/view a new tab will appear regardless of that same table already being opened, instead I would expect to get switched to the tab that's already opened.

This seems to be happening for all databases. This can be easily implemented with a hashmap containing the table name (which would be the tab name also) and a value containing the id or sequence of the tab. Every time a table is clicked try to access the hashmap, if the key is there, show the tab with the id, if not, follow legacy code.

**Comment by rathboma** [comment]
Hey! The reason it does this right now is that you might have the table open with different filters... so it just opens the table again. I'm planning on reworking this in future so that foreign key clicks open in the sidebar first, then optionally open in table view. I think that'll allow me to have one tab per table without messing up filters.

**Comment by rathboma** [comment]
I'm going to close this issue, because rather than solving it directly I think it'll be streamlined with the introduction of a sidebar.
