### ISSUE TITLE
QUESTION: Is this repo stagnant?

### ISSUE THREAD

**Issue by runtimeinteractive** [beekeeper-studio/beekeeper-studio#1255]
I feel like I've been looking at the same PR's and an ever increasing list of feature/bug requests for the application. The last commit by the developer was like 11 days ago and it seems like he dislikes merging PR's from other contributors. 

Is this repo still active or is the developer too overwhelmed by the influx of requests?

**Comment by Zerotask** [comment]
What's the point of your issue?
If you look at the commit history, then you can see that Beekeeper Studio is actively developed.
Feel free to contribute to this project ;)

**Comment by Celuni** [comment]
PR something valueable and not small things

**Comment by runtimeinteractive** [comment]
> What's the point of your issue?
> 
> If you look at the commit history, then you can see that Beekeeper Studio is actively developed.
> 
> Feel free to contribute to this project ;)

If you read the title, you'd see that it's a question not an issue and there's no need to get defensive.

I'm only asking because I truly believe in this project and would hate for it to fall over.

**Comment by runtimeinteractive** [comment]
> PR something valueable and not small things

There are valuable PR's still pending. It's not about who has the biggest PR, it's about functionality.

**Comment by theOofDoctor** [comment]
I mean I've seen multiple PRs merged into master recently, as well as @rathboma replying to issues fairly quickly. This isn't his full time job, give the guy some credit

**Comment by rathboma** [comment]
Hey! No it's not stagnant. I'm a one-person maintainer team, so sometimes progress is slow.

For the last few weeks my father has been visiting from the UK for the first time since before the pandemic (3 years!), so I've been less active than usual.

I'm glad you like the project enough that you want it to move faster -- I do too! The best way to help me do that is to buy the [Ultimate Edition](https://www.beekeeperstudio.io/pricing/) - with enough customers I can go full time on this project.
