### ISSUE TITLE
FEAT: Entities (tables list) show amount of records directly

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#1258]
**Is your feature request related to a problem? Please describe.**
I always have to open a specific table to know if there are records (rows) in it.

**Describe the solution you'd like**
To save time, the Entities (table) list could directly show the amount of records. This could be checked / updated in the background, if you activate it in the settings.

Basic example how it could look like
![image](https://user-images.githubusercontent.com/20150243/172000948-302c9bcb-20c3-43a8-befe-612f427b0136.png)

**Describe alternatives you've considered**
Check it manually.

**Comment by rathboma** [comment]
You know, I had a PR to do this, but fetching record numbers has created a number of issues, that's one reason we don't do it by default anymore even on the TableTable view.

I'm going to close this issue, not because I don't think it'd be cool, I just can't see this being a priority in the next 12-18 months.
