### ISSUE TITLE
BUG: int64s not displaying properly

### ISSUE THREAD

**Issue by dacz** [beekeeper-studio/beekeeper-studio#1399]
**Describe the bug**
In sqlite columnt with type INTEGER containes uint64. Beekeper displays normal int (very probably because it is JS UI and JS has no native support for bigint/int64.

**To Reproduce**
1. Save big enough uint64 number (eg. number bigget than from go)
2. Diplay listing in "view data"

Example: `326335020369620480` becomes `326335020369620500`

**Expected behavior**

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: OSX
 - App Version Version 3.6.6 (3.6.6)
 - Database type and version [sqlite3]

Probably need to use bigint js lib?

**Comment by rathboma** [comment]
Thanks!

**Comment by davidkaufman** [comment]
Reviewed SQLite3 data types docs at https://www.sqlite.org/datatype3.html#affinity_name_examples re: its uBigInt default beahvior, and was able to readily recreate the bug:

~~~sql
CREATE TABLE
  `test_bug1399` (
    `id` integer not null primary key autoincrement,
    `test_text` TEXT null,
    `test_int` INT null,
    `test_bigint` BIGINT null,
    `test_ubigint` UNSIGNED BIG INT null
  );

INSERT INTO test_bug1399 VALUES (
  null,
  326335020369620480,
  326335020369620480,
  326335020369620480,
  326335020369620480
);
~~~

![image](https://user-images.githubusercontent.com/2336122/207214267-8fa25cf8-727d-4189-a116-b97e8196d5c9.png)

And also determine that it is, in fact, only a display issue, by examining the same row with the sqlite3 cli: 
~~~sql
dkaufman@bender beekeeper-studio % sqlite3 test_bug1399.sqlite
SQLite version 3.28.0 2019-04-15 14:49:49
Enter ".help" for usage hints.
sqlite> select * from test_bug1399 ;
1|326335020369620480|326335020369620480|326335020369620480|326335020369620480
sqlite>
~~~
we can see that the value was stored correctly in the sqlite database

**Comment by davidkaufman** [comment]
So, after mucking around with mutators and cellFormatters I realized that the problem is not *really* a display issue, but lies in the how the `better-sqlite3` module that we use populates the result set objects as data is read from the db, because that's when the value gets rounded down to the lower precision, when it's stored in a JS `Number` variable instead of 
a `BigInt`)

So I dug into the `better-sqlite3` docs and found it does provides is a lever we can pull for this:

* [WiseLibs/better-sqlite3/docs/integer: The BigInt primitive type / Getting BigInts from the database](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/integer.md#getting-bigints-from-the-database)

so first I tried flipping that bit:

~~~diff
diff --git a/apps/studio/src/lib/db/clients/sqlite.js b/apps/studio/src/lib/db/clients/sqlite.js
index 41f04fc0..69f594b8 100644
--- a/apps/studio/src/lib/db/clients/sqlite.js
+++ b/apps/studio/src/lib/db/clients/sqlite.js
@@ -640,6 +643,12 @@ async function runWithConnection(conn, run) {
   let db
   try {
     db = new Database(conn.dbConfig.database)
+
+    // bind integer columns to BigInts by default
+    db.defaultSafeIntegers(true);
+
     const results = await run(db)
     return results
   } finally {
~~~

which threw some startup errors in the console such as:

~~~js
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: Do not know how to serialize a BigInt"

found in

---> <DatabaseDropdown> at src/components/sidebar/core/DatabaseDropdown.vue
       <CoreSidebar> at src/components/sidebar/CoreSidebar.vue
         <Sidebar> at src/components/common/Sidebar.vue
           <CoreInterface> at src/components/CoreInterface.vue
             <App> at src/App.vue
               <Root>
vue.runtime.esm.js?cdb3:3019 TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at toJSON (object.js?a511:137)
    at eval (index.js?f960:47)
    at Array.reduce (<anonymous>)
    at Object.transform (index.js?f960:45)
    at transport (ipc.js?c8c7:34)
    at runTransport (log.js?4c34:44)
    at runTransports (log.js?4c34:27)
    at log (log.js?4c34:21)
    at eval (sqlite.js?c314:611)
~~~

Fortunately googling "***TypeError: Do not know how to serialize a BigInt***" turned up a similar issue in the (similar project) Prisma:

* https://github.com/prisma/studio/issues/816

so I was able to resolve that by adding another one-liner, up near the top of the same file:

~~~diff
diff --git a/apps/studio/src/lib/db/clients/sqlite.js b/apps/studio/src/lib/db/clients/sqlite.js
index 41f04fc0..69f594b8 100644
--- a/apps/studio/src/lib/db/clients/sqlite.js
+++ b/apps/studio/src/lib/db/clients/sqlite.js
@@ -22,6 +22,9 @@ const sqliteErrors = {

 const PD = SqliteData

+// Fixes "TypeError: Do not know how to serialize a BigInt"
+BigInt.prototype.toJSON = function() { return this.toString() }

 export default async function (server, database) {
   const dbConfig = configDatabase(server, database);
~~~

And those 2 lines of code fixed the problem observed in the table viewer

![image](https://user-images.githubusercontent.com/2336122/207897852-98a11583-1a18-4761-b1bb-fb622ce56f98.png)

But (there's always a but...) I still have some housecleaning to do.  When I drop & recreate the table, for instance:

~~~js
[Vue warn]: Error in render: "TypeError: Cannot read property 'toPrecision' of undefined"

found in

---> <QueryEditorStatusBar> at src/components/editor/QueryEditorStatusBar.vue
       <QueryEditor> at src/components/TabQueryEditor.vue
         <CoreTabs> at src/components/CoreTabs.vue
           <CoreInterface> at src/components/CoreInterface.vue
             <App> at src/App.vue
               <Root>
vue.runtime.esm.js?cdb3:3019 TypeError: Cannot read property 'toPrecision' of undefined
    at VueComponent.shortNum (QueryEditorStatusBar.vue?57fe:155)
    at eval (QueryEditorStatusBar.vue?9827:60)
    at Proxy.renderList (vue.runtime.esm.js?cdb3:2001)
    at Proxy.render (QueryEditorStatusBar.vue?9827:49)
    at VueComponent.Vue._render (vue.runtime.esm.js?cdb3:2654)
    at VueComponent.updateComponent (vue.runtime.esm.js?cdb3:3844)
    at Watcher.get (vue.runtime.esm.js?cdb3:3415)
    at Watcher.run (vue.runtime.esm.js?cdb3:3491)
    at flushSchedulerQueue (vue.runtime.esm.js?cdb3:4090)
    at Array.eval (vue.runtime.esm.js?cdb3:3113)
~~~

And one of the unit tests isn't too happy about unexpected BigInts either because 1n == 1 but it doesn't === 1 🙄 but we should be getting there soon.

**Comment by rathboma** [comment]
Great update, thanks!

**Comment by davidkaufman** [comment]
Guessing there are more places where this breaks other code, I ran the tests to see where some of those places might be.  Here are the results so far of the automated test suites at this point:

# 1. Integration tests (clean checkout):

~~~bash
cd ~/dev/bks/beekeeper-studio/apps/studio
dkaufman@bender studio % yarn test:integration
~~~
~~~js
yarn run v1.22.19
$ TEST_MODE=1 ELECTRON_RUN_AS_NODE=1 yarn electron ../../node_modules/jest/bin/jest.js
$ /Users/dkaufman/dev/bks/beekeeper-studio/node_modules/.bin/electron ../../node_modules/jest/bin/jest.js

 RUNS  tests/unit/lib/db/clients/mysql.spec.js
 RUNS  tests/unit/lib/db/clients/sqlite.spec.js
 RUNS  tests/unit/lib/db/clients/postgres.spec.js
 RUNS  tests/unit/common/appdb/models/saved_connection.spec.js
 RUNS  tests/unit/lib/db/clients/sqlserver.spec.js
 RUNS  tests/unit/lib/db/clients/cockroachdb.spec.js
 RUNS  tests/unit/lib/db/clients/utils.spec.js

Test Suites: 6 failed, 2 passed, 8 total
             ^^^^^^^^
Tests:       245 failed, 30 passed, 275 total
Snapshots:   0 total
Time:        700.043s
Ran all test suites.
~~~
But after applying the changes above:
~~~js
Test Suites: 7 failed, 1 passed, 8 total
             ^^^^^^^^
~~~

Heres the new test failure I introduced into the integration tests:
~~~js
  ● Sqlite Tests › Common Tests › column filter tests

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Array [
        Object {
          "created_at": null,
    -     "job_id": 1,
    -     "person_id": 1,
    +     "job_id": 1n,
    +     "person_id": 1n,
          "updated_at": null,
        },
      ]

      424 |   async columnFilterTests() {
      425 |     let r = await this.connection.selectTop("people_jobs", 0, 10, [], [], this.defaultSchema)
    > 426 |     expect(r.result).toEqual([{
          |                      ^
      427 |       person_id: this.personId,
      428 |       job_id: this.jobId,
      429 |       created_at: null,

      at DBTestUtil.columnFilterTests (tests/lib/db.ts:426:22)
      at Object.<anonymous> (tests/integration/lib/db/clients/all.js:36:5)
~~~

# 2. Unit tests:

~~~bash
cd /dev/bks/beekeeper-studio/apps/studio
dkaufman@bender studio % yarn test:unit
~~~

All 11 unit tests passed both with and without these changes 😀 

Not sure why i wasn't able to recreate the unit test failure about 1n not being === 1 but I'm sure it will rurn up again :-)

But anyway, no help from the test suite detecting regressions in vue modules like the one in the `QueryEditorStatusBar` editor component above so... back to the drawing board on that ☹️

**Comment by davidkaufman** [comment]
I was able to resolve the integration test failures by running them one at a time, and to save a lot of testing time by just running the sqlite tests (thanks, @wmontgomery!)

Here is a new test that proves the error:
- https://github.com/davidkaufman/beekeeper-studio/commit/88428f36186d0e7f95cf17246a298123c993a3fc

Submitting a PR for the fix shortly

**Comment by davidkaufman** [comment]
PR Submitted!
- https://github.com/beekeeper-studio/beekeeper-studio/pull/1463
