### ISSUE TITLE
Simple SQL Statement returning strange hash

### ISSUE THREAD

**Issue by FezFamiliar** [beekeeper-studio/beekeeper-studio#1409]
Hello Everyone.

I am trying to run this simple query:

```SELECT CONCAT('Total nr of orders in january is ', COUNT(*)) AS nr_of_payments FROM payments WHERE paymentDate >= '2005-01-01' AND paymentDate <= '2005-02-01'```

but unfortunately I get this weird hash output:

```546f74616c206e72206f66206f726465727320696e206a616e756172792069732035```

![image](https://user-images.githubusercontent.com/26207930/197552779-6c823749-e5ec-46c1-b782-a61afcee44b5.png)

I am using the latest beekeper studio which is 3.7.1 and I'm on windows

Note that I tried different mysql clients like workbench and Heidi and it works well in those clients. Please fix it.

EDIT: its not a hash its the hex representation of Total nr of orders in january is 5. But still, why is this happening?

**Comment by rathboma** [comment]
This is happening because the database is interpreting the result as binary and giving beekeeper a byte array as the result.

That's weird. I wouldn't expect concat to do that.

Reading the MySQL manual this is expected, to solve cast the integer as a chat/string:

SELECT CONCAT(CAST(int_col AS CHAR), char_col);

See also https://github.com/mariano/node-db-mysql/issues/55

Hope that helps.
Going to close this, if it comes up again we'll figure out a better fix
