### ISSUE TITLE
QUESTION: Connecting to Redshift fails

### ISSUE THREAD

**Issue by khadnot-dc** [beekeeper-studio/beekeeper-studio#1451]
**Details:**
With the same credentials I used with DBeaver, I'm unable to connect to my clients Redshift database. The error I'm getting is "no pg_hba.conf entry for host". Are there any drivers I need to install to use Beekeeper Studio?? Thanks so much!

**Version Information [might be relevant to your issue]**
Operating System: macOS 13.0.1
App Version [help -> about]: 3.7.10
Database type and version [eg Posgresql 9.3]: PostgreSQL 8.0.2

**Screenshot / GIF [if appropriate]**:
<img width="548" alt="Screenshot 2022-12-12 at 2 36 10 PM" src="https://user-images.githubusercontent.com/112977276/207170767-73b75f3a-46c3-49ef-85d9-b0e6cb7376b1.png">

**Comment by kenn-data-clymer** [comment]
Has anyone else encountered this before? I'd really like to get this fixed before I buy a license.

**Comment by davidkaufman** [comment]
Hi @khadnot-dc,

The error in your screenshot `no pg_hba.conf entry for host` means that, on the database server side, postgres is not configured to accept a direct db connection from your Mac's IP address (see https://stackoverflow.com/questions/1406025/no-pg-hba-conf-entry-for-host for more about how to configure the `pg_hba.file` server on the db server side)

I'm not that familiar with Amazon Redshift, but if it doesn't allow you to edit the `pg_hba.conf` file, there are a couple of other things you can try:

1. You can [check if your Redshift cluster is ***configured to require SSL connections***](https://aws.amazon.com/premiumsupport/knowledge-center/redshift-troubleshoot-connection-errors/#Invalid_operation_connection_error) and if it is, you would need to turn on Beekeeper Studio's "Enable SSL" option in the connection settings (which appears to be off in the screenshot you posted).

2. and, since you can connect to this database using DBeaver, you might have configured DBeaver to connect using an SSH Tunnel (and maybe a JumpHost too) through an ec2 server that is local to the Redshift network and so *is* allowed to connect.  So you might want to check your [DBeaver connection profile and Network Settings](https://github.com/dbeaver/dbeaver/wiki/SSH-Configuration) to see if those are setup and, if so, you can configure the same SSH and JumpHost options in Beekeeper Studio!

**Comment by khadnot-dc** [comment]
That was it! Just needed to enable SSL. Thanks so much!
