### ISSUE TITLE
FEAT: Can you refer to SQLyog for interface design?

### ISSUE THREAD

**Issue by fredeason** [beekeeper-studio/beekeeper-studio#1475]
Personally, I think the best one is SQLyog, but there is no macos version of this software: I don’t know if the following can be considered:
1: Double-click a table to view the data (view all data in the table) whether the results can be displayed on the Query Result page
2: Connection information on the left, database, table, can these be changed to display all connection information on the left in a tree structure (mainly refer to sqlyog)

![Demand](https://user-images.githubusercontent.com/19574910/211753225-95c30c83-b0a0-48c6-be35-4f3f579d8027.png)

**Comment by rathboma** [comment]
Hi! Yes these are important UI considerations. We've thought about them a lot, but for now we've decided to stick with the UX mantra of `no tabs within tabs`. I think navigating tabs is fairly easy, as is opening two Beekeeper windows to have them side by side.

Even with tabs in the bottom pane you still have to switch between them! I think a split view would also help fix this in future.

For now I'm going to close this issue, not because I don't think there are optimizations to be made here, I just want our current UI plan to shake out first before addressing.
