### ISSUE TITLE
Redshift Connection throwing Error

### ISSUE THREAD

**Issue by ankurs24** [beekeeper-studio/beekeeper-studio#150]
When trying to connect to Redshift database, I get an error:
**"column el.typarray does not exist"** and the connection does not succeed.

Same error happens when trying to connecting using Potgres connector. I suspect it's gotta do with some version issue of Postgres. 

https://github.com/dbcli/pgcli/issues/316

**Comment by rathboma** [comment]
Ok, I'll take a look. I may have introduced this error myself :-S

**Comment by joeschmid** [comment]
In case it helps, I'm getting the same error when connecting to Redshift.

**Comment by pointtonull** [comment]
Not sure if helps, but a bisect on releases gave me:

first-bad:1.3.0
last-good 1.2.0

(GNU/Linux Mint/Ubuntu)

**Comment by maxbreakwell** [comment]
This seems to have come up again.

I just noticed it today, though I am not sure how long the bug has actually been present. I also use Beekeeper with several MySQL databases, which I am connecting to and querying much more often than Redshift. 

I was using the most recent version of Beekeeper, 4.6.8, and I had to go all the way back to 4.1.13 in order to find a version where I could connect without this issue coming up. 

Redshift 1.0.75379 PostgreSQL 8.0.2
