### ISSUE TITLE
BUG: Error when using ssh tunnel

### ISSUE THREAD

**Issue by diogor** [beekeeper-studio/beekeeper-studio#1562]
**Description**
Cannot connect using ssh tunnel, receive error: "all configured authentication methods failed."
Connecting through terminal with same credentials works.

**To Reproduce**
1. Configure a new connection using ssh tunnel
2. Select SSH Authentication: Key File
3. Select default private key (generated with ssh-keygen without password): /home/user/.ssh/id_rsa

**SSH server log**
`userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`

**Version Information (please complete the following information):**
 - OS: Arch Linux
 - App Version: 3.7.10
 - Database type and version: PostgreSQL v14.4

**Comment by davidkaufman** [comment]
Hi @diogor 

Can you provide more info on the server O/S and version that your'e trying to connect to?  Other users have reported issues with Ubuntu 22.04 no longer accepting RSA ssh keys. See:

- Bug #1240

If this is affecting you, the best workaround might be generating a DSA key to use instead of (or in addition to) your RSA key.  

Another is to reconfigure the server to accept RSA keys again, as described here:

- https://github.com/beekeeper-studio/beekeeper-studio/issues/1240#issuecomment-1377942140 adding `PubkeyAcceptedKeyTypes=+ssh-rsa` to `/etc/ssh/sshd_config` on server

Hope this helps!

**Comment by bilogic** [comment]
https://ikarus.sg/rsa-is-not-dead/

To be more specific, RSA keys are still accepted. Only RSA keys with SHA-1 signatures are deprecated. My point being: this is something the clients can correct.

**Comment by ckdake** [comment]
This problem will apply when tunneling through Amazon Linux 2023 unless it is configured to allow legacy crypto:  https://docs.aws.amazon.com/linux/al2023/ug/ssh-host-keys-disabled.html

**Comment by davidkaufman** [comment]
The ssh2 module has been upgraded in PR #1653 so this should be fixed in the next release!

**Comment by davidkaufman** [comment]
And, to correct my earlier misinformation:

@davidkaufman wrote:
> If this is affecting you, the best workaround might be generating a DSA key to use instead of (or in addition to) your RSA key.

As i discovered in Bug #1648. DSA keys are no longer accepted either -- the workaround is to create either an ECDSA or ED25519 key with `ssh-keygen -t ecdsa` or `ssh-keygen -t ed25519`

But RSA keys will work on Ubuntu 22 again in the next release so, hopefully no workaround will be necessary soon!

**Comment by davidkaufman** [comment]
This has been fixed in #1648 with the upgrade of the ssh2 module from 1.110 to 1.14.0 (PR #1653)
