### ISSUE TITLE
Ability to create schemas.

### ISSUE THREAD

**Issue by AqilCont** [beekeeper-studio/beekeeper-studio#162]
I would really like a graphical interface for creating new schemas on the MySQL editor. It would add some more simplicity to the workflow.

**Comment by rathboma** [comment]
While I think this definitely helps accessibility, this is certainly not something we have the bandwidth to add right now, nor can I see this being a core feature for a while.

I think instead we're probably better served providing templates for table creation and letting folks view the DDLs for existing tables.

I'm going to close the issue to keep the issue tracker clean -- this doesn't mean I think your issue is unimportant, but we just aren't capable of building this right now.
