### ISSUE TITLE
BUG: Cannot connect to Azure Postgres server, can connect using dbeaver or pgadmin with same settings

### ISSUE THREAD

**Issue by ishan-flek-ai** [beekeeper-studio/beekeeper-studio#1648]
**Describe the bug**
Cannot connect to Azure Postgres server, can connect using dbeaver or pgadmin with same settings

**To Reproduce**
- Azure Database for PostgreSQL flexible server Private
- Virtual Machine - login via SSH key
- SSL enabled

**Expected behavior**
Connection should happen

**Screenshots / Gifs**
No error message is displayed

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 3.8.9 (3.8.9)
 - Database type and version Posgresql 14.7

**Additional context**
Should atleast give the error message so that steps can be taken to resolve or so that we can report the error here. Same config is working fine on Dbeaver or pgadmin.

**Comment by not-night-but** [comment]
Is there an error in the console?

**Comment by ishan-flek-ai** [comment]
Updated still getting the error

error watch null postgresql
tunnel.ts:49 tunnel/ GOT TUNNEL PORT 10000
tunnel.ts:57 tunnel config:  
{fromPort: 10000, toPort: 5432, toHost: 'removed to not expose db URL'}
ConnectionInterface.vue?215b:78 error watch Error: All configured authentication methods failed
    at doNextAuth (/Applications/Beekee…ib/client.js:803:21)
    at tryNextAuth (/Applications/Beekee…lib/client.js:993:7)
    at USERAUTH_FAILURE (/Applications/Beekee…ib/client.js:373:11)
    at 51 (/Applications/Beekee…lers.misc.js:337:16)
    at Protocol.onPayload (/Applications/Beekee…Protocol.js:2025:10)
    at AESGCMDecipherNative.decrypt (/Applications/Beekee…ol/crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (/Applications/Beekee…Protocol.js:1994:25)
    at Protocol.parse (/Applications/Beekee…/Protocol.js:293:16)
    at Socket.<anonymous> (/Applications/Beekee…ib/client.js:713:21)
    at Socket.emit (node:events:390:28) postgresql

**Comment by not-night-but** [comment]
Hmmm weird. That looks like it's just a password issue, but weird that it's just not showing up in the client

**Comment by davidkaufman** [comment]
Hi @ishan-flek-ai 

This might be a duplicate of the existing issue:
- #1240

Recent releases of the sshd server (particularly in Ubuntu 20+ and now, appaerently, Azure Postgres instances) have a new default configuration that no longer accepts the older, standard, default RSA private key format.  It is a pretty nasty breaking change, seeing as how many linux distros still generate keys in RSA format by default and, worse, the error message is not very helpful to users suddenly encountering this problem.

While we're  waiting for [the ssh2 node module](https://github.com/mscdex/ssh2/) that Beekeeper Studio relies on for its ssh functions, to merge (a patch that fixes this)[https://github.com/mscdex/ssh2/compare/master...ext_info] that fixes it, the simplest workaround is for you to generate a new ssh keypair, specifying one of the newer types, either DSA or ECDSA

`ssh-keygen -t dsa` or `ssh-keygen -t ecdsa`

And try connecting to your PG db on Azure using that key, instead.  Please let us know if this resolves your issue!

thanks. 

-dave

**Comment by davidkaufman** [comment]
In trying to recreate this, I created a free Azure account and setup two Azure Database for PostgreSQL flexible servers, one using "Public" networking and the other "Private" (only accessible to my private Azure vnet / virtual network)

Neither appears to allow ssh access (Authentication options are: Postgres auth or Azure Active Directory auth), so I assume @ishan-flek-ai also setup a Virtual Machine (Linux server) to access it, as [the docs suggest](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/quickstart-create-connect-server-vnet) so I setup one of those too.  The default Virtual Machine was an Ubuntu 20, but I chose an Ubuntu 22.04 since we've had other users report problems connecting to the latest Ubuntu 22 machines.

To test ssh access to the virtual machine I created a user, generated different types of keys by adding them to my `~/.ssh/authorized_keys` file on the sever, and
tested using ssh:

- ✅ an RSA key `~/.ssh/id_rsa` - the RSA DID allow me to ssh into the server
- ❌  a DSA key `~/.ssh/id_dsa` - the DSA did NOT let me ssh into the server
- ✅ an ECDSA key `~/.ssh/id_ecdsa` the ECDSA key DID let me ssh into the server, and
- ✅ and an ED25519 key `~/.ssh/id_ed25519` ED25519 DID let me ssh into the server

So my advice to try generating a new key with `ssh-keygen -t dsa` was apparently wrong 😲

Bu that's just the `ssh` command line client -- what about Beekeeper Studio?

So I installed the psql client (`apt-get install -y postgresql-client`) on my `test-ubu22` virtual machine and confirmed that _**it**_ was able to connect to the Azure Database for PostgreSQL flexible server using the `psql` command line tool from the virtual server:

~~~bash
dkaufman@test-ubu22:~$ psql -h pg14-flex.postgres.database.azure.com -p 5432 -U pgadmin postgres
Password for user pgadmin:
psql (14.8 (Ubuntu 14.8-0ubuntu0.22.04.1), server 14.7)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=>
~~~

Notice that it reports that the postgresql server is running on ubuntu 22.04 also, and that the `psql` client is connecting using SSL and TLS 1.3

So I then tried to connect to this Azure Database for PostgreSQL flexible server using Beekeeper Studio, using the different types of ssh keys and, sure enough, choosing either the the RSA or DSA ssh keys in Beekeeper, I got the same error as @ishan-flek-ai: "`Error: Error: All configured authentication methods failed`"

But choosing either the ECDSA or ED25519 key, I was able to connect to Ubuntu 22.04 Virtual Machine.

However, i still haven't been able to connect to postgres db -- I either get a timeout or a "connection refused" error.  So i'm troubleshooting that, but can confirm that:

### When using an Ubuntu 22 ssh host, although the `ssh` client lets you login using a standard/default RSA key, Beekeeper's Studio's `ssh2` module cannot not.

So the workaround is to generate a new ssh key using `ssh-keygen -t ecdsa` or `ssh-keygen -t ed25519` and use that key for Beekeeper Studio.

I'm doing a test upgrade of our ssh2 module to see if that fixes the problem, but in the meantime, I hope this helps.

**Comment by davidkaufman** [comment]
Good news!  After upgrading the ssh2 from `ssh2` v1.11.0 to 1.14.0, Beekeeper Studio can again use `rsa` ssh keys to log into Ubuntu v22 servers again!  This fix should be in the next release.

**Comment by davidkaufman** [comment]
This is merged so should be fixed in the next release!

**Comment by davidkaufman** [comment]
I'm able to connect to my test Azure Database for PostgreSQL flexible now.  Unfortunately, I don't know which one of these things i tried worked:

- On the virtual machine I added `AllowTcpForwarding yes` to the `/etc/ssh/sshd_config.d/50-cloudimg-settings.conf` and restarted sshd (`sudo systemctl restart sshd`)

- I read this Azure TLS connection troubleshooting page: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl

- I downloaded the [DigiCert Global Root CA](https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem) that it mentions some "applications require" and added that to the Beekeeper Studio SSL connection options under "CA Cert (optional)"

- in the Azure Database for PostgreSQL flexible server "Server Settings" page I searched for `require_secure_transport` (which was On) and turned it Off

None of these changes worked when I first tried them -- I kept getting the "Disconnected due to timeout" error.  And, one by one i undid each of them except the `sshd` config file change.  And at some point it just randomly started working 🙄 

So now I _no longer_ have the CA Cert file showing in my Beekeeper SSL options, and i have the `require_secure_transport` setting turned back on in Azure, and I can connect to the posgres db through the ssh tunnel.  Sorry I'm not sure which change finally made it work tho...

Until the next Beekeeper release, with the ssh2 module upgrade, you should be able to connect using either an ECDSA or ED25519 ssh key generated using `ssh-keygen -t ecdsa` or `ssh-keygen -t ed25519` to get past that "All configured authentication methods failed" error

**Comment by ishan-flek-ai** [comment]
Just wanted to say that connection is working fine after the recent update. Thanks a lot for fixing this. Also love the tool and we would consider using the pro version after we raise funding :D
