### ISSUE TITLE
4.0 Autocomplete regressions

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1721]
There are a few regressions with autocomplete, I want to collect them all in one place for easy review and fixing.

- [ ]  #1720
- [ ] Autocomplete is quoting table aliases, which breaks the query - example `LEFT JOIN film as flm on a.id = flm.` <- autocomplete successfully finds the alias `flm` and the column names, but adds quotes around it `"flm"`, which breaks the query as this is not a formal identifier. See vid below

## Testing

Because our autocomplete system is not a real language server it is very brittle, and easy to break. That means we need to have a test suite. V1 test suite should be tackled as part of this issue.
- Tests should NOT require the DOM or CodeMirror
- We should include both of the above issues as explicit test cases
- Make it really easy to add a new test case for when we experience new regressions 

### Quoting table aliases

[Screencast from 09-29-2023 01:42:53 PM.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/6078e51d-4991-43b6-b0b3-e47242c4566e)

**Comment by azmy60** [comment]
Just looked at the [test](https://github.com/codemirror/codemirror5/blob/master/test/sql-hint-test.js#L12) file from the codemirror repo. It turns out we can use schemas without modifying the core file, and it's that easy :exploding_head:. So stupid of me lol... I feel like we can save ourselves all that parsing completely!
