### ISSUE TITLE
Ok Ok, only one tab should be open per table

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1854]

**Comment by Z3rio** [comment]
> @rathboma
> 
> Absolutely not necessary to put such a limit. I spend a lot of time browsing the same table with different filters at the same time.

Perhaps a setting for this can be added.
Or, just making it harder to accidentally open more tabs for your table.

Personally, I often find myself instinctively clicking the table in the list as I'm used to that bringing the table up into my view, but instead, I end up creating an entirely new tab, which isn't really that nice in my opinion.

**Comment by SuzukiRyuichiro** [comment]
I second this one, I hope by default, if you hit Cmd + P and choose a table, I would like to go back to already opened table than opening a new one, similar to VScode. I often find my self needing to deep clean the tabs, and because there are so many one off queries that are unsaved, it doesn't go as smooth....

**Comment by azmy60** [comment]
Yes, opening a new tab for a table was a bug. Closing this in favor of #1834.
