### ISSUE TITLE
Oracle database support

### ISSUE THREAD

**Issue by BuZZ-dEE** [beekeeper-studio/beekeeper-studio#20]
Please add support for the Oracle database.

**Comment by rathboma** [comment]
Will do! I'll keep this around until it's done. Probably won't be in the next release.

**Comment by jskrable** [comment]
Any timeline for this? I'd love to switch from DBeaver but I can't make the jump until Oracle is supported. Thanks for your work!

**Comment by lealhugui** [comment]
> Any timeline for this? I'd love to switch from DBeaver but I can't make the jump until Oracle is supported. Thanks for your work!

Same here....

If you need a hand with the code, I can send you a PR.

**Comment by rathboma** [comment]
@lealhugui that would be 100% amazing.

**Comment by flopezre** [comment]
Please 🙏🙏🙏

**Comment by jeffschaper** [comment]
> Any timeline for this? I'd love to switch from DBeaver but I can't make the jump until Oracle is supported. Thanks for your work!

Same here. I'd love to switch over from Dbeaver, but our business uses Oracle as their primary DB source

**Comment by netesheng** [comment]
Please 🙏🙏🙏

**Comment by emresebat** [comment]
Hello is there any progress on this? I really liked Beekeeper, probably the best open source tool I've seen as a SQL client with nice UI. I could help with Oracle support also 👍

**Comment by feesma** [comment]
Hello there!, First of all thanks for this awesome tool, is there any update into this?

**Comment by krokyk** [comment]
Much desired here, too!

**Comment by rathboma** [comment]
Hey all! It will probably be the next database we integrate with. My guess based on current workload is that we manage to do this in Q1 2022. Sorry it's not sooner, but always happy to accept PRs :-)

**Comment by MiguelGalrao** [comment]
Hey! 
How are things around there? 
Been waiting for this to change from DBeaver as well.

**Comment by MiguelGalrao** [comment]
Well, I can't say I am surprised.
The move to lock this feature as a Ultimate Edition exclusive makes Beekeeper a no for me.
It's true that we were never promised to get this feature on the free version of the product, but it's also true that since the beginning, no indication of this happening was given, so I'm surprised that you choose to lock database compatibility behind a pay-wall, but at the same time I was already expecting it.
Nothing good comes free I guess.

Personally I will still use DBeaver or other freemium program that is compatible with multiple DBs.
Students, hobbyists and even people that just want to explore will be forced to pay if they want this feature, and probably so many others that will come.

To me it doesn't make sense, the compatibility should be there for us all, the more professional workloads should be behind that pay-wall, but you have the numbers and the data to back your decision, I just hope it allows you to grow to a point where you can expand the free version capabilities without hurting your business.

Good luck and keep up the good work!

**Comment by BuZZ-dEE** [comment]
@rathboma I'm also really disappointed about to make this an "Ultimate" feature.

**Comment by rathboma** [comment]
Hey all! It's hard to figure out where to draw the line between free and paid.

If I could make everything free, I would.

Unfortunately I spend 40% of my work week on Beekeeper Studio, but my Beekeeper revenue is ~0. It needs to become sustainable for me to be able to continue that investment.

The general rationale I'm using for ultimate is: FOSS databases -> free version, commercial databases -> ultimate version. I figure that if a business can pay for a database like Oracle, they can pay for a database tool like Beekeeper.

Let me know if I'm totally off base here and you are all using Oracle for side projects or something like that?

**Comment by rathboma** [comment]
@BuZZ-dEE @MiguelGalrao Can I ask where you are using an Oracle database? At work or in some other context?

**Comment by MiguelGalrao** [comment]
> @BuZZ-dEE @MiguelGalrao Can I ask where you are using an Oracle database? At work or in some other context?

Hey again, yes of course.
I recently finalized my degree in Software Engineering and had multiple projects that used Oracle DBs because of some partnerships with my university.

We also used Postgres and some non-relational DBs but we started with Oracle.

Having still access to those educational licenses, and as you’ve said, being a more enterprise oriented DB (being that is paid), I would like to continue explore it in my free time.

Granted I can use other software to manipulate my data, or even use another technology, Postgres is also interesting. 

I understand your point above about the decision between free/paid database compatibility, as I’ve said before I (and most people here) don’t have the data to make an educated decision, so our opinion is just that, an opinion. 

I guess the main take away for me is that I like to tinker and try new stuff, and most of the community I encounter falls into the same bucket, that’s how I found you, in my search to substitute DBeaver in a Linux environment.

Of course you must draw the line somewhere and you won’t be able to please everyone, just make a decision that makes the most sense to you and the team behind this :)
If my needs lead me away from Oracle I know where to find you, until then I am afraid I can’t.

All the best and keep it up!

**Comment by scrambldchannel** [comment]
Hey

I've been kicking the tyres of Beekeeper for a couple of weeks and so far so good, thanks @rathboma and everyone else :) I thought I'd offer my feedback, it's the least I can do.

> The general rationale I'm using for ultimate is: FOSS databases -> free version, commercial databases -> ultimate version. I figure that if a business can pay for a database like Oracle, they can pay for a database tool like Beekeeper.
> 

Leaving aside what some people think of paywalls, I'd agree this seems to be a totally reasonable place to draw the line.

> Let me know if I'm totally off base here and you are all using Oracle for side projects or something like that?

I'm only having to deal with Oracle _precisely_ because someone I'm working for is paying for it. This is a bit of an anomaly in that they're not an enormous org. Somewhat counter intuitively, that might even make it more likely that they might let me spend their money on Beekeeper. This is arguably changing, but I think huge corporates are _less_ likely to let developers pay for tools like this, even though it's a pittance to them (procurement processes etc). 

Also @MiguelGalrao, although I'm digressing a bit, I can understand why Oracle and the like set up these partnerships (not sure what's in it for the unis) but but if you get knocked back for a relatively junior role on the basis that you know Postgres, not Oracle, it would be a massive red flag for me about the hiring manager anyway. You may not have this luxury, of course, but I think a team that doesn't understand that 95% of those skills are transferrable probably isn't one I'd want to join.

Anyway, I'll put my soapbox away and download my trial version ;)

**Comment by rathboma** [comment]
Here's a preview of my current Oracle build, it's working, but half broken.
![Peek 2022-04-20 21-21](https://user-images.githubusercontent.com/279769/164358927-784a1f03-c037-4227-a72f-3d4609623585.gif)

I'm going to get this to a 'working' state for read-only tables and structure, then push out a release.

**Comment by TobiTenno** [comment]
> If you're not a student, write a blog post about how you use Beekeeper Studio (500 words+, original content only, must link to our website, must stay online for a year!), send me the link, and I'll give you a free copy of ultimate

Personally, I'd happily do this and keep it up for as long as I use beekeeper, which is the forseeable future.

> When showing the tables in the sidebar `[...]`

I'd expect to have them all available, but also be able to hide based on permission (which I'd assume would already be the case? like that if you don't have perms to see them, beekeeper wouldn't read them with extra magic)

**Comment by rathboma** [comment]
@TobiTenno yes that is how it would work, I'm literally just doing `select * from all_tables`. Ok good to know about the other schemas

**Comment by gnovaro** [comment]
For example Oracle offer "Oracle Database XE"  (Express Edition) is limited version for development enviroment for free https://www.oracle.com/uk/database/technologies/appdev/xe.html

I think free version can have the ability only for connect to this version. If you pay for Oracle you can pay for the tool too..

**Comment by jremerich** [comment]
Hi!

To help on this, I work with postgres as primary database but the company that I work for has Oracle as his primary, so we transfer data from oracle to pg and vice-versa.

The Oracle's DBA uses oracle tools as SQL Tools, SQL Developer and etc... He doesn't need (and don't want to) another DB tool. But I, as PG administrator, need to connect in both databases, basically to troubleshooting, because the data syncronization.

I understand and agree with your decision about paid/free versions, but can I suggest a trial period? Just to tests on production databases... We have many database procedures, functions and triggers and almost all this tools are be able to edit it but isn't all of them that do this on the right way...

Thanks for your work, it's just an amazing tool!!

**Comment by rathboma** [comment]
Thanks so much :heart: 

I'm going to do an Ultimate Edition release on Monday with `beta` oracle support, all the screens work, queries, tables, and schema views work too, but editing tables and schemas are not yet implemented

**Comment by rathboma** [comment]
Quick update - it took a week longer than expected, but beta Oracle Database support is now live in Beekeeper Studio Ultimate Edition.

Beta means - read only schemas and tables. The next version will provide full editing support too.
