### ISSUE TITLE
BUG: Cannot copy to the clipboard in Vim mode using the Yank command

### ISSUE THREAD

**Issue by agirorn** [beekeeper-studio/beekeeper-studio#2062]
I'm unable to copy to the clipboard when I'm in Vim mode by using the Vim Yank command.
I have to use <CMD>+C to copy to the system clipboard.

I have tried to configure the *~/Library/Application Support/beekeeper-studio/.beekeeper.vimrc* by setting `clipboard` to unnamedplus and unnamed and they do not work.

Beekeeper Studio: Version 4.2.5 (4.2.5)
Mac: 13.4.1 (c)

**Comment by rathboma** [comment]
Thanks for the bug report!

@not-night-but wanna take a look?

**Comment by not-night-but** [comment]
@agirorn Just filed a pull request for this, so you can track that to get updates on this fix.

A note:
Because of how codemirror's vim mode works, we can't just set this as a default behaviour, as their vim mode has no knowledge of the system clipboard. This means that you have to do what you'd do in vim, select a register and then do the action (eg `"*y` to yank to system clipoard). If this is a default behaviour you want, you may be able to add a keybinding in the vimrc after this has been merged to map `y` to `"*y` and `p` to `"*p`

**Comment by jtourlamain** [comment]
@not-night-but how can I map y to "*y? Adding `vmap y "*y` doesn't work (recursive). And using vnoremap doesn't seem to work either

**Comment by not-night-but** [comment]
@jtourlamain Looks like there's a bug when mapping to those specific actions. They are mapped, but when trying to use those mapping it seems the call stack is exceeded. I'll file an issue for that, but I'm not sure if we will be able to fix it
