### ISSUE TITLE
BUG: TableTable ctrl+arrow movement breaks cell selection

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2078]
How to replicate:

1. Open a table table and click a cell on the table
2. Moving the arrow keys should correctly navigate the table
3. Press ctrl+down-arrow

Expected:
- Cell 1,100 should be selected
- Pressing arrow keys continues to navigate the table

Actual:
- Cell 1,100 is selected
- Pressing the arrow keys does nothing

The same happens if you press ctrl+up from anywhere below the scrollable area. It seems causing the table to scroll breaks keyboard navigation.

Also: ctrl-arrow is also bound to changing the page number, this should be removed in favor of table navigation

**Comment by azmy60** [comment]
I can comment out the `Ctrl+left/right` for page navigation. But do you think we should have this in config file as well?

For now, the easiest solution is disabling them.

The non easy solution is we can use `Alt` instead of `Ctrl` but tabulator can capture that (it captures all arrow keys regardless if it's used or not).
