### ISSUE TITLE
Retain LF/CR on copy or save

### ISSUE THREAD

**Issue by MrBretticus** [beekeeper-studio/beekeeper-studio#273]
Provide a similar feature/option to SSMS
![image](https://user-images.githubusercontent.com/253641/89618880-50e1e480-d8d0-11ea-8746-9d11ea908ea7.png)

**Comment by rathboma** [comment]
So I understand this -- this means there are CR/LF values at the end of your actual database values and you want to retain them when you copy a cell value or export the table. Is that right?

**Comment by UtechtDustin** [comment]
Currently all new lines are broken, you can test it with this SQl:
```
SELECT "SOME TEXT

WITH NEW LINES
" as TextWithNewline
```
![Bildschirmfoto von 2020-08-10 17-22-09](https://user-images.githubusercontent.com/13292481/89799693-17a6b000-db2e-11ea-8a14-a537bbf81704.png)

The cause is the tabulator, currently the type of the cells is "plaintext", which dont support new lines (see documenation).
So should use a formatter or something like that which replace newlines with newline symboles.

Just a quick idea :-)
