### ISSUE TITLE
BUG: Slow render time when opening table in tab due to counting rows

### ISSUE THREAD

**Issue by LeeMendelowitz** [beekeeper-studio/beekeeper-studio#311]
**Describe the bug**

When previewing the content of the table, the tab is very slow to load (on the order of 10+ seconds) if the table is large (has millions of rows). This is because BeeKeeper is issuing a `SELECT COUNT(*) from table;` statement to display the number of rows at the bottom left corner of the tab, and this query takes several seconds to run. A simple select against the table runs fast (`SELECT * FROM table LIMIT 1000;`).

I am connecting to a MySQL 5.7.22 database and counting rows on an InnoDB table.

**To Reproduce**
1. Navigate to a table with millions of rows and click the "Open in a new tab" button

**Expected behavior**
I would expect the table preview to load quickly, and then the table row count to load in the lower left corner after a delay once all the rows have been counted. Perhaps there could be an option to not produce table row counts, since `SELECT COUNT(*) from table` runs slowly and generates work for the database.

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 1.7.4

**Additional context**
I am connecting to a MySQL 5.7.22 database and counting rows on an InnoDB table.

**Comment by UtechtDustin** [comment]
For Mysql we could use  
```
show table status like 'TABLE'
```

**Comment by rathboma** [comment]
So some background here:

We need some indicator of table size at the beginning to enable table pagination. That said we should probably move to a two-phase system:

1. Initially fetch an approximate count of records, [example for MYSQL ](https://dba.stackexchange.com/questions/184685/why-is-count-slow-when-explain-knows-the-answer/184746#184746)
2. When the first page has loaded, fetch an accurate count to replace it

This will also be a problem for PSQL / SQL Server / ETC, basically anything with a b-tree index.

**Comment by dhrrgn** [comment]
Just ran into this issue with one of our tables in a PosgreSQL DB, which has 11+ million rows.  Here are some notes:

## Getting an approximation in PostgreSQL

Here is an example to get a fast approximation (replace `TABLE_NAME` and `NAMESPACE` with correct values):

```sql
SELECT
  ROUND(
    (reltuples / relpages) * (
      pg_relation_size('TABLE_NAME') / (current_setting('block_size')::integer)
    )
  )
FROM
  pg_class
where
  relname = 'TABLE_NAME'
  and relnamespace::regnamespace::text = 'NAMESPACE';
```

It runs in milliseconds, and is generally within a couple thousand rows.  Which, when you are dealing with millions, is acceptable for display / guessing number of pages.

## Use count(*), not count(1)

I noticed you are using `count(1)` [in the client](https://github.com/beekeeper-studio/beekeeper-studio/blob/master/src/lib/db/clients/postgresql.ts#L289).  This is actually slower.  Not much, but it is slower.  This is because `count(*)` is calling an aggregate function with no parameters, where `count(1)` is sending and analyzing the parameter, so the planning time is slower.

## Duplicate count queries

I noticed that just selecting a table in the sidebar (at least on large tables), causes it to run 6 identical count queries.  This only exacerbates the slowness issue on large tables.  

Seems you should be able to just 1?

## Only get exact if needed

> When the first page has loaded, fetch an accurate count to replace it

Not sure this is necessary or a good idea.  On large tables, a count query could end up using a lot of CPU time, slowing down other queries.

My suggestion would be to only get the exact count if under a certain threshold, like 10 times the page size.  Then, for those with approx counts, only fetch the exact count if trying to go to a page near the end.

Otherwise, there is no real reason for the exact count IMO.  You can denote it is approx. in the status bar with a `~`

**Comment by rathboma** [comment]
Thanks for the great detailed comment. I'll be working on these issues this week!

**Comment by dhrrgn** [comment]
> The duplicate counts was a mistake introduced by making the table schema refresh on table-open to avoid the issue where schemas were stale.

Ya, I actually pulled down the repo and did some debugging and found the same thing (`dataFetch` called multiple times).

FWIW, Tabulator has a `ajaxRequesting` callback, which aborts the request if it returns `false`. This may be useful to avoid executing duplicate queries.

A simpler solution could just be to add an async memoize function (there are great open source packages for this) and wrap all query calls with that. 

Something like:

```js
const response = await memoizeAsync(this.connection.selectTop(/* ... */));
```

Could make it easier on the consumers and do it in the client, but there may be times where you don't want the memoization.

**Comment by rathboma** [comment]
@dhrrgn Why do you do all that math with the `reltuples`? The postgres wiki just suggests returning `reltuples` as the approximate row count:

https://wiki.postgresql.org/wiki/Count_estimate

Is there something the wiki misses?

**Comment by dhrrgn** [comment]
Ya, that is not as accurate. To get a better approximation, you need to take the physical table size into account. 

From the PostgreSQL docs on [how the planner estimates row counts](https://www.postgresql.org/docs/current/planner-stats.html#id-1.5.13.5.3):

> In any case, the planner will scale the values it finds in pg_class to match the current physical table size, thus obtaining a closer approximation.

**Comment by rathboma** [comment]
interesting, I'll use your query then, thanks!

The duplicates are simply because I'm not managing state properly. I already have it fixed.
