### ISSUE TITLE
Query stops at 50,000

### ISSUE THREAD

**Issue by jamesmhusseyjrdev** [beekeeper-studio/beekeeper-studio#366]
Queries stop at 50,000 results
Version  Postgresql
Operating System: WIN10 PRO

**Comment by gravatite** [comment]
I ran into the same problem with Postgres in the Ubuntu version, and there doesn't seem to be a way to change that limit that I can find.

**Comment by KasperFranz** [comment]
It is a project maximum: https://github.com/beekeeper-studio/beekeeper-studio/blob/cf48d75412142d635196769939bb6cc1561b0adb/src/config.ts#L39

**Comment by rathboma** [comment]
This is a sanity limit right now to stop folks ddosing their machines. Soon I'll be implementing a file paging feature so you can get the full result set. 

Sorry this is inconvenient right now!

**Comment by jamesmhusseyjrdev** [comment]
Hi Matthew,
Thanks for the update.

**Comment by mdc-git** [comment]
Hi Matthew,

I deeply appreciate your work on this great project. Thank you. Keep it up!

DISCLAIMER: I am a total Vue noob. But I tried to hack this in myself. I have zero experience, so YOU'D BETTER NOT USE MY CODE. I was only interested in quick & dirty MySQL/CSV Export. I'm sure, I BROKE some things by accident.

I'd just like to add a few points. Turns out, it's actually fairly hard for me to get paging done right in the TabQueryEditor with a freestyle query. 

- The first thing I tried was a local pagination which somewhat seemed working, but ran out of memory eventually with big resultsets (> 400000 rows). I guess, that's why the maxresults=50000 is in place. Downloads didn't work. Maybe partly related to the "reactive" behaviour of Vuejs, which doesn't play too well with huge arrays.

- Then I thought about remote pagination, so I tinkered with some code from the TableTable component and copied some parts to ResultTable. Suppose, we wan't a row limit of 1000 per page.
- First off, you might have to parse the query, because it could contain a limit and an offset by itself, ordering might also be contained. So you need to get some semantics. (like limit,offset,ordering)
- Then you can build queries mix matching your fixed pagination scheme into the original values. (get total rowcount, build pagination queries,...) 
- If you use a fixed pagesize you might need to apply some weird paging shifting calculations e.g. you want to display a fixed page size of 1000, but the originial was like limit 5001 with an offset of 5.
- Sorting this asc and desc can be cumbersome in this scenario. Or maybe I'm just dumb.
- The download has to be done  separately to get the full resultset, as the remote paged Tabulator only knows about pagesized data afaik. And setting all rows to Tabulator is not an option because of memory. Again with respect to the originally typed limits offsets and ordering from the original query.

I just thought I'd share my experiences just in case you or someone else might be interested.

**Comment by dlong500** [comment]
@rathboma I'm trying to see if I can move from SQLYog to BeeKeeper Studio, but the hard-coded 50k results is a deal-breaker (even if it is just in the editor).  You mentioned implementing a file paging feature but it still seems like nothing has changed.  I have enough tables with more than 50k records that this is an absolute requirement.  SQLYog can handle it without issue (just queried a 90k+ table w/ 50 fields and the memory usage sits at around 160MB even after scrolling through the entire resultset).  Even with the 50k limit Beekeeper stutters while scrolling through the results.

I keep wanting to like Beekeeper (and am even willing to pay for the Pro plan) but this just doesn't seem like a SQLYog alternative at the moment.
