### ISSUE TITLE
QUESTION: any plan to support nosql like mongodb?

### ISSUE THREAD

**Issue by roeniss** [beekeeper-studio/beekeeper-studio#379]
**Details:**
I'm wondering if beekeeper-studio has some plan to provide support for nosql.

**Comment by rathboma** [comment]
A common question! Yes, hopefully, but probably not for a while because we don't want to add any sort of half-baked support into the app. When we do it, we will do it properly :-).

If you sign up for the newsletter on the website (go to a blog article) we'll announce it when it's done (I only ever post announcements to the newsletter).

Going to close this issue because it is a duplicate of #258

**Comment by BrunoLagoa** [comment]
It would be incredible to have the mongo implemented! I support the suggestion
