### ISSUE TITLE
BUG: Prevent Double click from opening a table twice

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#469]
**Describe the bug**
If you double click a table name it opens it twice. It should only open it once.

Taken from #465

**Comment by mhatvan** [comment]
@rathboma I took a look at this issue and in my opinion the problem is the following:

```
<span
  class="item-wrapper flex flex-middle expand"
  @click.prevent="openTable"
  @dblclick.prevent="openTable"
>
```

There is a double click and a single click listener on the list item. This actually results in 3 opened table tabs for me on my end.
I guess the double click gets triggered once while the single click gets triggered twice.

What should the behavior be so that I can make some code adaptions? Single click only or double click only to open a table?

**Comment by rathboma** [comment]
It is intended to be single-click only. I think we'll need to re-evaluate about the single/double click behavior at some point, it still doesn't feel quite right.

**Comment by WNemencha** [comment]
Hey Beekeepers!

First thanks for the awesome great work on Beekeeper Studio, it's a pleasure to use and I've encountered almost no issue with it after some months of usage! :)

I was asking the same question in my head: 
why are there multiple tabs for the same table? (no offense, I understand its a bug 😛)

Common UX would be that **1 tab = 1 table**.

Also, about the "single/double click behavior" you mention;  
please use common UX here too: **1 click = selection, 2 clicks = primary action (i.e. open table tab)**.

my 2 cents ^^

**Comment by rathboma** [comment]
We have some changes coming for table interaction! Stay tuned

**Comment by WNemencha** [comment]
Just updated to v1.12.0 and it seems like its now working like all the other native apps! Hooray 🎉 💯 
Props to the peoples that implemented this small (but life changing) one ;)
