### ISSUE TITLE
FEAT: Run query, results go directly to a file.

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#472]
Provide a special function to allow a user to run a query and export the results directly to a file.

Why? The normal query window has (sensible) max result limits to prevent UI lock up. This would allow a user to query 40mm records and send them to a json,csv,markdown,etc file (same ones we support for exports)

## Feature discovery
- Add a `Run to file` button to the `RUN` dropdown.
- Add something to the `download` dropdown to do the same thing
- Add some sort of tooltip when a user hits the 50k limit to signify this feature is available. Don't show it again if they've dismissed it.

## Implementation

This should be fairly easy and use the same `BeeCursor` implementations we already use for exports. Right now this work will have to happen in the main UI thread as we have no background framework. Note to self / others: Do not try and build a background job processing framework as part of this ticket, that is out of scope.

## UI / UX Sketches

![PXL_20230102_214116874](https://user-images.githubusercontent.com/279769/210280044-b972648a-1266-42cd-968a-8de0471f5a60.jpg)

**Comment by rathboma** [comment]
OH wait, what's that? #601 is coming :rocket:

**Comment by davidkaufman** [comment]
This is working now for CSV files, tested with 10K and 100K rows from a mysql table.  Still need to debug why a million-row export failed silently, and see about examining the query result to get the columns names because the JSON export is doing the col_0, col_1 thing again, since you can't examine the table to get the column names for an arbitrary sql query -- you have to examine the resultset.

**Comment by davidkaufman** [comment]
![image](https://user-images.githubusercontent.com/2336122/219709462-b4394001-5e30-4783-8539-88e19fd1df0d.png)

Debugging the progress indicator lol

**Comment by davidkaufman** [comment]
Good news! Actually the million-row mysql export succeeded!  I had only _thought_ it failed silently because the bug in the ExportNotification (shown above) was not reporting any progress and, understandably, it takes a while to run!  But after quite a while (10+ minutes? i'll time it next time) it _**did**_ export a complete million row CSV file:

I've only tested mysql (actually MariaDB).  Working on that `NaN` bug in the notification now, since without the user can't TELL if its working 😏 

~~~js

dkaufman@bender beekeeper-studio-fork % ll -h ~/Downloads/query_export_2023-02-20_063747-1MM.csv
-rw-r--r--  1 dkaufman  staff   389M Feb 20 06:47 /Users/dkaufman/Downloads/query_export_2023-02-20_063747-1MM.csv
                                ^^^^
dkaufman@bender beekeeper-studio-fork % wc -l ~/Downloads/query_export_2023-02-20_063747-1MM.csv
 1000000 /Users/dkaufman/Downloads/query_export_2023-02-20_063747-1MM.csv
 ^^^^^^^
~~~

~~~python
head -n 10 ~/Downloads/query_export_2023-02-20_063747-1MM.csv | less
2,MANHATTAN,1077287,1230,6TH AVENUE,123725807,01,A2,Y,01264,00005,105,10020,2,,MID,,OT,ISSUED,RENEWAL,EW,02,OT,,NOT APPLICABL
3,STATEN ISLAND,5113169,715,OCEAN TERRACE,500876037,01,A2,Y,00683,00001,502,10301,2,,NA-1,,OT,ISSUED,RENEWAL,EW,03,OT,,USE UN
4,BROOKLYN,3253458,9952,3 AVE,321963014,01,DM,N,06133,00056,310,11209,1,,BR,,,ISSUED,INITIAL,DM,01,,,USE UNDER 300 CU.YD,2020
5,BROOKLYN,3117942,179,LOTT STREET,322006618,01,DM,N,05136,00058,317,11226,1,,,,,ISSUED,INITIAL,DM,01,,,ON-SITE,2020-06-17,20
6,BROOKLYN,3210296,2917,AVENUE  N,321996970,01,DM,N,07665,00004,314,11210,2,,,,,ISSUED,INITIAL,DM,01,,,ON-SITE,2020-06-17,202
7,BROOKLYN,3055183,245,FRANKLIN AVENUE,340735789,01,A3,Y,01927,00006,303,11205,2,YES,,,EQ,ISSUED,INITIAL,EQ,01,OT,,,2020-06-1
8,BROOKLYN,3169308,338,BAY 10 STREET,340734904,01,A2,Y,06460,00310,311,11228,1,YES,,,OT,ISSUED,INITIAL,EW,01,OT,,NOT APPLICAB
9,MANHATTAN,1079152,333,W 17TH STREET,103651709,01,A2,Y,00741,00010,104,10011,2,,,,OT,ISSUED,RENEWAL,EW,02,OT,,NOT APPLICABLE
10,BROOKLYN,3184453,1855,E 26 ST,340734085,01,A2,Y,06832,00064,315,11229,1,YES,,,OT,ISSUED,INITIAL,EW,01,OT,,NOT APPLICABLE,2
11,BROOKLYN,3132159,1864,60TH STREET,340733969,01,A2,Y,05519,00034,312,11204,1,YES,,,OT,ISSUED,INITIAL,EW,01,OT,,NOT APPLICAB

tail -n 10 ~/Downloads/query_export_2023-02-20_063747-1MM.csv | less
999992,QUEENS,4017085,23-83,33 STREET,420056619,01,A1,N,00834,00005,401,11105,1,YES,,,EQ,ISSUED,INITIAL,EQ,01,FN,,NOT APPLICABLE,2010-08
999993,MANHATTAN,1057054,243,RIVERSIDE DRIVE,100963487,01,A3,,01887,00001,107,10025,2,,,,OT,ISSUED,INITIAL,AL,01,,,NONE,1995-01-26,1995-
999994,BROOKLYN,3157847,1627,72 STREET,320391376,01,A2,N,06181,00082,311,11204,1,YES,,,OT,ISSUED,INITIAL,EW,01,OT,,NOT APPLICABLE,2011-1
999995,STATEN ISLAND,5148776,22,EL CAMINO LOOP,500628537,01,NB,Y,06979,00216,503,10309,1,YES,,,,ISSUED,RENEWAL,NB,04,,,ON-SITE,2007-07-1
999996,BRONX,2092092,250,WILLIS AVENUE,200033597,01,A2,,02283,00001,201,10454,2,,,,OT,ISSUED,INITIAL,EW,01,OT,,NONE,1990-05-24,1990-05-2
999997,BROOKLYN,3259250,62,PARK PLACE,302570901,02,A2,Y,00941,00050,306,11217,2,,,,MH,ISSUED,RENEWAL,EW,06,MH,,,2020-01-22,2020-01-22,20
999998,MANHATTAN,1001409,100,CHURCH STREET,100196093,03,A2,,00125,00020,101,10007,2,,,,MH,ISSUED,INITIAL,EW,01,MH,,NONE,1994-10-03,1994-
999999,MANHATTAN,1035455,437,MADISON AVENUE,110003166,02,A2,Y,01285,00021,105,10022,2,,,,MH,ISSUED,INITIAL,EW,01,MH,,NONE,2007-10-26,200
1000000,MANHATTAN,1088207,2,COOPER SQUARE,104743422,01,A2,,00544,00065,102,10003,2,,,,EQ,ISSUED,RENEWAL,EQ,03,FN,,NONE,2008-12-23,2008-1
1000001,MANHATTAN,1042369,160,EAST   65 STREET,102711077,01,A2,,01399,00033,108,10065,2,,,,PL,ISSUED,INITIAL,PL,01,,,NONE,2000-08-24,200
~~~

**Comment by davidkaufman** [comment]
Actually 4 buglets:

When doing an export of a _*filtered*_ table, the percentage complete in the progress notification is calculated using the rowcount of the entire table, and doesn't take into account the filter so, for instance, exporting 50,000 rows from my million row test table, it goes: ..., ..., ..., ..., ..., 1%, ..., Done.  shoule be. simple fix (right? (...as if anything's ever simple.))

**Comment by davidkaufman** [comment]
Conditional Download is now working and provides a nice option for users suprised / disappointed that their over 50K row result set was truncated -- now they can export it 😃 

![Download-truncated-resultset](https://user-images.githubusercontent.com/2336122/229157232-81a20cef-5e2c-4a70-86ef-82b4d8016ca8.gif)

This screen recording also shows:

- The need for some UI feedback in between execution of large queries and their actual display (many seconds of frozen ui), and 
- How slow my computer is 🤣

**Comment by davidkaufman** [comment]
This PR should be good to go
- #1503

**Comment by davidkaufman** [comment]
This fix should be available in an upcoming release.

In the meantime, if this is affecting you and you have a dev build, here is the patch:
- ae42124043e
