### ISSUE TITLE
FEAT: Search/Replace in query editor

### ISSUE THREAD

**Issue by moisespsena** [beekeeper-studio/beekeeper-studio#552]
Hello!

I have been looking but I haven't found a way to `search` and `replace` in query editor.

**Comment by rathboma** [comment]
Correct, that is not implemented yet. good idea though!

**Comment by agalazis** [comment]
That's the only thing missing for me xD specially for big queries

**Comment by steo-ml** [comment]
Was about to request for this, glad I searched it up first. Excited to see this feature soon!

**Comment by rbdmorgan** [comment]
+1000

Honestly this is the only thing stopping me from buying a license (and why I'm still half looking elsewhere!)

Otherwise it's perfect!

Every time I instinctively hit CMD+F I'm like "ur, where's search? Is something wrong with my keyboard?!" 😉

I'm literally having to paste the query out to VS Code, search (and replace) there and paste back to Beekeeper!

Please add this @rathboma, pretty please 🥺

**Comment by rbdmorgan** [comment]
Also requested here #1501 and here #1230.

Seems like it's been on the way for a while? Accepted as an enhancement Feb 2021 (above) and again May 2022 (#1230).

Any update @rathboma? I see you planned to bundle this into [Version 4.5](https://github.com/beekeeper-studio/beekeeper-studio/milestone/9) (announced May 2022 but no progress or due date yet) though that appears to include some pretty complex Postgres-specific stuff, whereas I think this missing find and replace is more fundamental (and hopefully _relatively_ straightforward?)
