### ISSUE TITLE
QUESTION: lack of fundamental features, disappointed.

### ISSUE THREAD

**Issue by adamsau** [beekeeper-studio/beekeeper-studio#554]
**Details:**
I find it totally unacceptable that there is a simple lack of fundamental features, like

create database/tables from left panel
editing table schema/add rows from the GUI
etc.

I decide to create this issue because at one point I cant wait to try this new database IDE,
start a simple workflow like creating databases and tables, yet the outcome was so disappointing.
I think you need to implement the IDE from an engineer perspective, like what they are trying to do and how they use it.
I hope there will be improvements in the future.

**Comment by UtechtDustin** [comment]
I can agree that fundamental features are missing, in my case this would be:

- create database (i already created a base of a PR for that #265)
- edit table schema
- add new entries (#525)
- import/export table(s)/database(s)

If that is done i could use beekeeper in production.
But we have to keep in mind that it is a free program and it can take a while until this is implemented.

So i think it makes more sense to implement the fundamental features first, before supporting more databases or to implement nice to have features.

**Comment by rathboma** [comment]
Hey! Thanks for being excited about the project! 

I know features are limited right now, but we have a dream and we're building towards it. We hope you can see our vision with these initial versions.

Right now we only have a few hours a week to work on the app, but in April I'm going to start spending 2 days a week, in order to knock out some of these core features.

So stick with us and we'll get there :-)

**Comment by rathboma** [comment]
Going to close this issue, not because I don't care, but because we're tracking things in other places.

If you have time, please do open new tickets if there are specific features you really care about!

**Comment by anilsg** [comment]
I know this issue is closed but I'd like to try to balance this feedback in the hope of advising future direction.

The most fundamental feature of Beekeeper Studio is that it is the best GUI database tool I know because it DOESN'T take the approach of all the others like Beaver, Toad, etc: namely - no massive collection of GUI features with hundreds of menus with multi-levels and dozens of crazy chord shortcuts that you never remember.

Beekeeper Studio is a matt black smooth and intuitive uncluttered interface that dovetails nicely with a CLI / data oriented engineers workflow. I know there are different camps / schools, of course, and perhaps the Windows oriented ("I need to do everything in a GUI with a mouse and only type names") school is the one that most often has the money to cough up, in which case I applaud @rathboma in serving those individuals, for the sake of the project.

But please don't sell your birthright to an interface which prioritises space for data and a minimal essential toolset to maximise the returns on a RISC approach.

For instance, database creation is not a fundamental feature. I am not sure there are people out there creating multiple databases every day but if there are, they are not going to be the majority and, excepting for the potential ingenuity with which Rathboma may implement such a feature, there's no need to pollute the interface just to do that. It is certainly not a fundamental feature, and it's got to be disingenuous to actually whine about that being missing. By all means suggest it, but complaining that database creation is an almost deal breaking fundamental omission? That's not credible.

When I need to create databases frequently it's for test reasons and I've got that scripted up anyway, because I don't want to have to point and type a hundred times, I just want to type "drop and reload". If you need to create a database manually, in that you're actually considering using your mouse to do it, it's not hard to run `$ psql ... > create database ...`.

I encourage an appropriate prioritisation for similar less frequently used features like schema edit. In an engineering context you have probably got generators for database creation anyway nor would you be pointing and clicking your way to incrementally change your database design on a daily basis (or shouldn't be ...). 

Thanks rathboma for an awesome tool. If anyone knows a better GUI database tool available this side of the galaxy please let me know.

**Comment by adamsau** [comment]
good to receive feedback here. I totally agree that for your workflow you prioritize on the data itself. There are also a lot of indie engineers that manage databases on their own and it is going to be painful if they need to resolve to looking up commands all the time. The reason not using dbeaver is that there are many areas where the UX sucks on its part. I guess the point here is labeling "fundamental" is too broad on its own, maybe "features for simple managing workflow" is more of an appropriate term.
