### ISSUE TITLE
FEAT: Table features in Query View

### ISSUE THREAD

**Issue by larrydewey** [beekeeper-studio/beekeeper-studio#592]
**Is your feature request related to a problem? Please describe.**
Currently, when performing a query, there are not interactive fields provided in the result set.

**Describe the solution you'd like**
It would be really nice to be able to perform the same kind of actions one has when accessing a table from the GUI:
- Editing Fields
- Following Foreign Keys
- Apply filters from the GUI

**Describe alternatives you've considered**
Obviously you can manually write a number of queries, but it would be a nice feature :) 

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)

Can edit data from the Table View:
![Table Edit Capability](https://user-images.githubusercontent.com/41640198/110711278-816a6380-81bc-11eb-9e43-0383aacfd5d0.png)

Can Follow Foreign Keys from the Table View:
![Follow Key Capability](https://user-images.githubusercontent.com/41640198/110711267-7dd6dc80-81bc-11eb-8cec-41f8e8b9aed1.png)

Sadly Lacking in the Query View:
![Lacking in Query](https://user-images.githubusercontent.com/41640198/110711286-83ccbd80-81bc-11eb-85cb-1211614cc0ee.png)

**Comment by rathboma** [comment]
Yes I agree it would be nice! Unfortunately a lot of the time the databases don't give us enough information in the results to infer everything we need. Also not sure how easy editing would be after a complex select query, the easy use-case of a simple select is probably a minority case.

I'm going to close this issue, not because I don't like it (I do!), I just don't know how to do this right now and won't be able to focus on it for the foreseeable future.
