### ISSUE TITLE
M1 ARM64 build for MacOS

### ISSUE THREAD

**Issue by joshuapack** [beekeeper-studio/beekeeper-studio#599]
Just FYI, I was able to run on Mac ARM64 using electron version 13.0.0-beta.5 fine. IDK if any bugs, but works great!

For my build:
https://github.com/joshuapack/beekeeper-studio

This is a major bump in Electron, and using a beta version at that. So, probably not exactly ready. But thought I should ping ya. It works VERY fast on the M1 Mac, compared to the Intel version at that. Major speed improvements.

I can continue to keep my forked version running until we get official release.

Thank you for this amazing program!

**Comment by rathboma** [comment]
AWESOME. Thanks so much for testing!

We just upgraded to Electron 9.xx from 8.xx, which is most of the upgrade work for moving to 11+ and supporting M1 Macs and Wayland Linux.

We'll be doing this soon :-). The biggest gap we have is the lack of a M1 based build machine.

Going to close this issue (because it's not really an issue), but very excited to hear your news :-), thanks!

**Comment by vitalyster** [comment]
Still an issue in version 1.11.5, please reopen to get people notified when it will be ready

**Comment by joshuapack** [comment]
> Still an issue in version 1.11.5, please reopen to get people notified when it will be ready

I have been keeping the M1 fork alive, and update it every release. But I can't wait until it become official.

**Comment by vitalyster** [comment]
@joshuapack maybe better to create a PR from your changes? That will increase chances to merge :)

**Comment by joshuapack** [comment]
@vitalyster I think it is a more of finding a way to build it, then it is on the code for it at this point.

**Comment by kevinfaveri** [comment]
> > Still an issue in version 1.11.5, please reopen to get people notified when it will be ready
> 
> I have been keeping the M1 fork alive, and update it every release. But I can't wait until it become official.

I can't build from your branch, it crashes on node-gyp when building sass if I remember correctly. 

I really miss an M1 ARM64 version since the non M1 is really laggy :(

**Comment by joshuapack** [comment]
> I can't build from your branch, it crashes on node-gyp when building sass if I remember correctly.
> 
> I really miss an M1 ARM64 version since the non M1 is really laggy :(

You can download the binary here https://github.com/joshuapack/beekeeper-studio/releases/tag/V1.12.0

I will see if I can fix that on my fork, I may just turn off other builds for my fork so that it won't crash, when I get time.

**Comment by kevinfaveri** [comment]
Hmm... But... It says to me that the executable is corrupted

**Comment by joshuapack** [comment]
Oh no, maybe I packaged the wrong file. Let me rebuild in a few.

**Comment by joshuapack** [comment]
@kevinfaveri ok, build it again, it will fail, but look in the folder `dist_electron/mas-arm64` and you should see the binary still built correctly. It looks like the build does not sign it, which is possibly why it fails and possibly why my binary doesn't work or says it is corrupted.

**Comment by ClumsyPenguin** [comment]
Commenting on this one, is there any updates on a up-to-date build for ARM apple M1?

**Comment by rathboma** [comment]
FYI I ordered an M1 Mac Mini today, so this is coming soon!

**Comment by joshuapack** [comment]
Awesome. I'm in the middle of moving, so I haven't been able to compile the latest version. 😭

**Comment by rathboma** [comment]
Hey folks, here's a download of the first working M1 build (see artifacts section):
https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/1948316196

This is signed, but not notarized, so you'll need to right click -> open to run it.

Some caveats:
- None! It's stupid fast. :-)

If anyone on this thread can test it themselves and let me know if they hit any errors that'd be helpful.

Otherwise the next release will also get an M1 version published, electron-updater should automatically upgrade itself from x86 -> apple, if not, simply replacing the original with the M1 version will do it.

**Comment by joshuapack** [comment]
I don't know if I'm doing it right. But I keep getting this. I'll look into it a bit deeper, just got my M1 Mac running again.

![image](https://user-images.githubusercontent.com/2073743/157569687-c7c93c2c-4dc5-4c8d-adb6-d333b0ea741d.png)

**Comment by joshuapack** [comment]
OK, i got it working. once notarized I think it will work perfectly!
