### ISSUE TITLE
Change result download link from automatically sending csv to a menu to select download format

### ISSUE THREAD

**Issue by dougmartin** [beekeeper-studio/beekeeper-studio#67]
Enhancement request:

Change the link here:

https://github.com/beekeeper-studio/beekeeper-studio/blob/b4d2b15f94a46ac6d18277582e241249754cff46/src/components/TabQueryEditor.vue#L38

to a menu allowing the user to select the various formats allowed by Tabulator (http://tabulator.info/docs/4.6/download):

```
csv - Comma separated value file
json - JSON formatted text file
xlsx - Excel File (Requires the SheetJS Library)
pdf - PDF File (Requires the jsPDF Library and jsPDF-AutoTable Plugin)
html - HTML Table file
```

then update this line to use the selected format:

https://github.com/beekeeper-studio/beekeeper-studio/blob/a82ea985f349dec6cf5ceb7bf6471de47c5a6c40/src/components/editor/ResultTable.vue#L67

if you don't want to add additional dependencies just support `csv`, `json` and `html`.

**Comment by rathboma** [comment]
Agreed, this would be useful.

I'm in favor of csv, json, and html to begin (no additional libs required).

This would actually be a great first issue for someone

**Comment by LoveSponge** [comment]
+1 for this, specifically excel (xlsx) would be especially useful

Thanks for this awesome project by the way, it's WAY better than Microsoft's own 'Azure Data Studio' which i converted from when i switched to linux. (i know it would have worked, but i never liked it, just used it because it was the most lightweight solution for me at the time. But BEEKEPER is WAAAAAY better!)

**Comment by UtechtDustin** [comment]
@rathboma isnt this issue/feature already implemented ?

**Comment by LoveSponge** [comment]
I've been happily exporting to xlsx since the last major update :grin:
