### ISSUE TITLE
BUG: Beekeeper does not read double quote (" ") for strings properly

### ISSUE THREAD

**Issue by shivendra90** [beekeeper-studio/beekeeper-studio#690]
**Describe the bug**
When running a query in a SQLite database, Beekeeper wrongly interprets double quotes as a column name, if at all there is a string involved in either a conditional or while concatenating two or more string data. It therefore gives out the error `No such column`.

**To Reproduce**
1. Open a locally saved SQLite database.
2. Enter a query that has a string operation (either concatenation or comparison)
3. Execute that query.

For example, this is a query that I wanted to run:
```
SELECT ORDER_HEADER.CUSTOMER_ID, (CUSTOMER_FNAME||' '||CUSTOMER_LNAME) AS NAME
	FROM ORDER_HEADER
    INNER JOIN ONLINE_CUSTOMER ON ORDER_HEADER.CUSTOMER_ID = ONLINE_CUSTOMER.CUSTOMER_ID
    WHERE ORDER_HEADER.ORDER_STATUS = "Shipped";
```
And it throws error: `Sqlite error: no such column: Shipped`. It's wrongly taking the comparison in where clause as a column. When replaced with single quotes, the query returns results.

**Expected behavior**
The query should run with the double quotes, as it runs with single quotes.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu] Kubuntu 20.04
 - App Version [e.g. help -> About Beekeeper Studio] 1.12.0

**Additional context**
The same query with double quotes runs fine on another IDE.

**Comment by rathboma** [comment]
Hmm, maybe this is a SQLite setting?

this is a engine to engine difference so usually outside the control of Beekeeper.

Do have more information about support for double quotes in SQLite?

**Comment by shivendra90** [comment]
All I know is that using double quotes in another IDE for example DB Browser for SQLite does not return anything similar.

**Comment by MasterOdin** [comment]
SQLite does have a quirk of a misfeature in that it does allow double quote string literals due to historical reasons: https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted. However, back in 2019, a new config setting was added that allowed disabling this feature, and it was recommended to do so. `better-sqlite` took that advice and disabled it by default in their [6.0.0](https://github.com/JoshuaWise/better-sqlite3/releases/tag/v6.0.0) release. Changing this setting would minimally require re-compiling better-sqlite3, that the gain is probably not worth it, and better to just right idiomatic SQL and use single quotes around strings, which is portable to other DBMS engines whereas double quotes isn't.

**Comment by rathboma** [comment]
Thanks for the background @MasterOdin, a fountain of knowledge as always!

Going to close this issue, but hopefully others find it if they have this issue.

**Comment by Davi-AlohaDev** [comment]
One way I've seen to resolve this error is by putting single quotes (' ') and not double quotes (" ").
