### ISSUE TITLE
FEAT: move saved queries to `PINNED`

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#785]
**Is your feature request related to a problem? Please describe.**
For some people saved queries could be hard to find since the icon for it is a star, which can be associated with favorites (which goes more in the direction of pinned tables).

**Describe the solution you'd like**
To improve the UX, we could remove the `Saved Queries` menu point and add those queries to the `PINNED` section.
This was the first place where I though my saved query will go to.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/20150243/131366289-b2adb807-5199-4e71-820d-01c56361a5eb.png)

**Comment by rathboma** [comment]
We definitely need to review where saved queries go (and clearly also the iconography). We want to give them more structure too (folders) so that we can move towards team-sync features with permissions.

I agree they're not very discoverable yet, not sure yet if I agree with the pinned suggestion, although I do like that it keeps everything on one screen, but I'm worried for some users it would make the pinned section way too big.

I'm going to close the issue - not because I don't agree that it is a problem, but more because I'm tracking it elsewhere.
