### ISSUE TITLE
FEAT: Possible new features

### ISSUE THREAD

**Issue by lowercase00** [beekeeper-studio/beekeeper-studio#885]
Hi guys.

I decided to open a single issue, since this is a collection of ideas I've been gathering for a while.
I mostly use Postgres with Postico on a Mac along with Beekeeper. I've been a former user of Sequel Pro (using MySQL), which was pretty amazing, and I quite like several things in Postico as well, so just a bit of context so you guys can understand where my suggestions come from.

I'm not the most proficient Vue dev, but I would be willing to contribute, wanted to get your thoughts and opinions on each suggestion so eventual contributions are more spot on.  Please forgive me if this is too much for a single issue, I couldn't find "discussions" for a more open ended post, and thought it would be better to concentrate everything in a single topic instead of cluttering the issues with tens of topics.

**1. One click to select**
I'm pretty used of selecting a row, specially in a table with lots of columns, this helps gives context on what I'm seeing and staying in place while lateral scrolling. At the moment, one click enters the "Edit" mode. I would like to suggest the one click to select the row, and then double click to enter the "edit" mode. This behavior is similar in Postico and Sequel Pro if I'm not mistaken. I find it frustrating when trying to select a row, and then having to click outside to leave edit mode without saving. This is mostly annoying on a big table, where there's no obvious "hazard free" place to click.

**2. Background color**
As much as I'm a big fan of dark mode in general, along the years I found that there's a sweet spot for data heavy applications in terms of background color. Total black backgrounds tend to drastically increase contrast, which can make the information less obvious. What I've found is that gray is the optimal color to keep the dark mode, while maintaining optimal data visibility. I know this can be (and probably is) pretty controversial, so I would suggest to have and editable background color.

**3. Columns/Lines clearer division**
I normally like to keep things as clean as possible, but I've found there are some scenarios that this can be confusing, so a minimal amount of separation can be beneficial. I would suggest to have really light alpha gray color marking the division between columns and rows. I have a great experience with Postico in that sense. I find it gives a great overview of the data separation and context in terms of row/column information. Again, this may be controversial, so could be an option for the user to chose.

**4. Shift between data/structure on the same tab**
As much as I like tabs, I've been finding confusing to switch between data and structure in Beekeeper. When I'm on a table, and click "structure" a new tab opens, but now this can be amongst a number of other tabs, and I normally want to see structure in the "table" context, and not as I totally separate thing. So I tend to prefer the approach to be able to switch between data/structure in the same tab (again a candidate for user preference). Also, when in the structure tab, and clicking data, so moving back and forth, every-time I click "data' a new tab opens, so this has been a bit annoying.

**5. Distinguish booleans from strings**
I've have a few tables with plenty of booleans, and it can get confusing to understand whether this is just a regular string or a boolean. Being a "magic" string, I would suggest to have some sort of different approach for booleans can be beneficial. The reasoning is similar to IDE's dealing with booleans in a different color/text format (like different color or italic for example).

**6. Hide system tables**
I can understand that this is crucial for quite a lot of people, but for me personally showing system tables (the green ones) is confusing, I end up with a gigantic list of "entities", even in a small database. I really like the division between tables and visions, it's awesome. But the system tables are not my favorite part.

**7. Short-cut to refresh**
I'm so used to using "Cmd + R" to refresh things on my Mac, that I miss this functionality in BK. Would be great to have shortcuts, and even better to have customizable shortcuts.

**8. Dedicated Icon to Export**
As of now, the "export" feature is an "engine" icon. I found that a bit confusing, I would suggest something like the "share" icon, or maybe an I/O icon to be able to add the import functionality later on.

**9. Import functionality**
It would be awesome to be able to import data in SQL, CSV or something similar. I don't recall Sequel Pro importing functionality, but I quite like Postico in that sense.

**10. Flexible Columns Positioning**
I really like to move columns around (change the order of columns), this could be a great addition. Sometimes I want to group columns with certain logic to visually understand context of a collection of rows. This is pretty useful when fast scrolling a table with several booleans columns. It would be great if I could just change the columns position.

**11.  ERD Diagram**
Sometimes is great to have the visuals for the database, but most of the softwares I've seen that does that are extremely complex and make this a difficult task to accomplish (Workbench and DBeaver for example), Would be awesome to have this builtin.

**12. Gather everything in a "Settings" Page**
I guess most of the topics I've written here will not obvious for everyone. Maybe there could be an "Global Settings" screen where the user could chose these options. Maybe bellow the "database", "favorites" and "run history" icons on the left column, somewhat similar to what VSCode has. Seems a great place to put settings on.

Again, sorry for the long post. Just though I would share my impressions after using Beekeeper for a while along with other clients. Let me know if you guys think these points can make sense or not. I would be happy to spend more time discussion each one of them, and contributing as well.

Again, thanks a lot for the product, awesome stuff you guys have built, thanks for sharing!

**Comment by rathboma** [comment]
Thank you so much for the detailed issue!

Many of these we're working on, or at least planning to work on.

The structure/data thing definitely needs some tweaking, but I think there's probably a middle ground that feels nice.

I'm trying not to overload what goes in a single tab. The benefit of a tabbed UI is that 'everything can be a tab', which reduces the complexity of each individual tab, but I do realize this might break down sometimes :-).

Many of your styling comments are things on my mind a lot, but like you said this can be subjective as there's always someone who doesn't like it! Certainly I prefer function over form, while keeping a clean and minimal appearance.

Some specific comments:

- Booleans vs strings is new, and actually a really good idea. I'll add that as a separate ticket. #894 
- ERD - Love it, but can't prioritize this until I'm able to work on the app full time, which means a sustainable revenue source
- One click row selection - There's a lot of selection stuff that needs updating, but that requires a tabulator upgrade, and some tabulator improvements. I'll get there :-)
- Export/Import stuff - yeah this is a big hole. The current table export was a HUGE feature, way bigger than I thought it would be, so I'm wary of doing this too quickly without a bunch of time to spend on it. I think this is my next big feature priority honestly.
- Settings - Yep. Put stuff in here if you want it on a future settings screen -> #197 


Going to close this issue because it's not really one thing, but it's awesome, and thank you so much for taking the time to write it. I'm glad to see my priorities for the app are broadly aligned with the things that people want :-)

**Comment by rathboma** [comment]
Thanks for lots of feedback! Could you open a separate issue for `hide system tables`. I have no idea why I didn't think of that. So obvious.

GUI Settings page is probably just a JSON editor view, or re-using the table view in a special way

**Comment by anilsg** [comment]
> Thanks for lots of feedback! Could you open a separate issue for `hide system tables`. I have no idea why I didn't think of that. So obvious.

https://github.com/beekeeper-studio/beekeeper-studio/issues/1320
