### ISSUE TITLE
FEAT: Show total count

### ISSUE THREAD

**Issue by mohanrajDev** [beekeeper-studio/beekeeper-studio#987]
**Is your feature request related to a problem? Please describe.**
Whenever applying filter results count not showing 

**Describe the solution you'd like**
I've opened the table rows after applying the filter results count mismatching 
Sometimes showing all rows count 
If clicked refresh button showing random count

**Comment by rathboma** [comment]
Hey! Yes this was actually removed due to performance problems in large databases.

Beekeeper now uses a count estimation for the table, and no-longer shows filter counts. It's something I'd like to add back in (optionally) with a settings screen, or have Beekeeper Studio auto-detect when it should/shouldn't use this.

I'm going to close this as not something I can fix right now, but I've tagged it in my settings ticket!

Tagging: #197

**Comment by mohanrajDev** [comment]
Thanks Beekeeper-Studio/Beekeeper-Studio
